

services:
  app:
    image: ghcr.io/know-ai-uh/ecdc_fe:latest
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - 8888:8000
    container_name: ecdc_fe
    restart: unless-stopped
    # command: 'sleep infinity'

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.docker/config.json:/config.json
    command: --interval 30