services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/know-ai-uh/ecdc_fe:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 8000:8000
    container_name: ecdc_fe
    command: "npm run dev"
    # command: 'sleep infinity'