services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/know-ai-uh/ecdc_fe:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: ecdc_fe
    # command: 'sleep infinity'